# Python-only provider. Ignore root package.json (that is for Vercel).
providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r backend/requirements.txt"]
